# Generated by Django 4.1.7 on 2023-02-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registation_date', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=55, verbose_name='name')),
                ('last_name', models.CharField(db_index=True, max_length=55, verbose_name='surename')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=55, verbose_name='otchestvo')),
                ('birth_date', models.DateField(verbose_name='birth')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('avatar', models.ImageField(upload_to='', verbose_name='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='balance')),
                ('wallet_id', models.CharField(blank=True, default=None, max_length=12, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account', verbose_name='wallet')),
            ],
        ),
    ]
