# Generated by Django 4.1.7 on 2023-02-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='registation_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
