# Generated by Django 4.1.7 on 2023-02-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_account_registation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
