# Generated by Django 4.1.7 on 2023-05-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_wallet_account_delete_account_delete_wallet_squashed_0008_remove_account_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='id',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(blank=True, default=None, max_length=12, primary_key=True, serialize=False),
        ),
    ]
